version: '3.1'

services:
  postgres:
    image: "postgres:10.6"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feeds
    ports:
      - "5432:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.99.100:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: on-failure
    hostname: kafka
  feedService:
    build: .
    image: tdanylchuk/feed-service:1.0.0
    environment:
      DB_HOST: postgres:5432
      DB_USER: root
      DB_USER_PASSWORD: admin
      DB_NAME: feeds
      KAFKA_HOSTS: kafka:9093
      FEEDS_TOPIC_NAME: feeds
    restart: on-failure
    depends_on:
      - postgres
      - kafka
    ports:
      - "8000:8000"