version: '3.1'

services:
  db:
    image: "postgres:10.6"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feeds
    expose:
      - 5432
    ports:
      - "5432:5432"